id:0432320005101171
Name:jobair hossain

In [1]:
import numpy as np

# 1. Define ID parameters and Matrix A
d1 = 1
d2 = 7

A = np.array([[d1 + 2, d2 + 1],
              [2 * d1, d2 + 2]], dtype=float)

print(" Matrix A Analysis ")
print("Matrix A:\n", A)
print("Shape:", A.shape)

det_A = np.linalg.det(A)
print(f"Determinant: {det_A:.4f}")
print("Rank:", np.linalg.matrix_rank(A))

eig_vals_A, _ = np.linalg.eig(A)
print("Eigenvalues:", np.round(eig_vals_A, 4))

if not np.isclose(det_A, 0):
    inv_A = np.linalg.inv(A)
    print("Inverse:\n", np.round(inv_A, 4))
else:
    print("Inverse: Does not exist (Singular Matrix)")

# 3. Value Change Experiment: Add +1 to element A[0, 0]
B = np.copy(A)
B[0, 0] += 1

print("\n Matrix B Analysis (Changed A[0,0] from 3 to 4)")
print("Matrix B:\n", B)
print("Shape:", B.shape)

det_B = np.linalg.det(B)
print(f"Determinant: {det_B:.4f}")
print("Rank:", np.linalg.matrix_rank(B))

eig_vals_B, _ = np.linalg.eig(B)
print("Eigenvalues:", np.round(eig_vals_B, 4))

if not np.isclose(det_B, 0):
    inv_B = np.linalg.inv(B)
    print("Inverse:\n", np.round(inv_B, 4))
else:
    print("Inverse: Does not exist (Singular Matrix)")

 Matrix A Analysis 
Matrix A:
 [[3. 8.]
 [2. 9.]]
Shape: (2, 2)
Determinant: 11.0000
Rank: 2
Eigenvalues: [ 1. 11.]
Inverse:
 [[ 0.8182 -0.7273]
 [-0.1818  0.2727]]

 Matrix B Analysis (Changed A[0,0] from 3 to 4)
Matrix B:
 [[4. 8.]
 [2. 9.]]
Shape: (2, 2)
Determinant: 20.0000
Rank: 2
Eigenvalues: [ 1.783 11.217]
Inverse:
 [[ 0.45 -0.4 ]
 [-0.1   0.2 ]]


**Comparison & Explanation**

1.**determinant change:**$\det(A) = (3 \times 9) - (8 \times 2) = 27 - 16 = 11$$\det(B) = (4 \times 9) - (8 \times 2) = 36 - 16 = 20$Increasing $A_{1,1}$ by $1$ directly increased the primary diagonal product by $1 \times A_{2,2} = 9$, raising the determinant from $11$ to $20$.

2.**rank change**: No, the rank remained 2 for both matrices. Since $\det(A) \neq 0$ and $\det(B) \neq 0$, both matrices are full-rank ($2 \times 2$) with linearly independent rows and columns.


3.**eigenvalues respond**:The trace of the matrix (sum of eigenvalues) increased from $12$ ($3+9$) to $13$ ($4+9$). Consequently, the eigenvalues shifted:Matrix $A$: $\lambda \approx 11.0$ and $1.0$Matrix $B$: $\lambda \approx 11.4$ and $1.6$

4.**Invertibility Difficulty**:Computationally, both require identical $O(n^3)$ / direct algebraic operations. However, numerically, Matrix $B$ is slightly more stable to invert because its determinant is larger ($20 > 11$), meaning it sits further away from singularity ($\det = 0$).



