Name:Jobair hossain
ID:0432320005101171

In [1]:
import  numpy as np
from sympy import Matrix
import  matplotlib.pyplot as plt
import seaborn as sns

In [2]:
student_id = "0432320005101171"
d1 = int(student_id[-1])
d2 = int(student_id[-2])

A = np.array([[d1 + 2, d2 + 1], [2 * d1, d2 + 2]], dtype=float)

def analyze_matrix(M, name):
    print(f" Analysis for Matrix {name}")
    print(f"Matrix:\n{M}\n")
    print(f"Shape: {M.shape}")

    det = np.linalg.det(M)
    print(f"Determinant: {det:.4f}")

    rank = np.linalg.matrix_rank(M)
    print(f"Rank: {rank}")

    eigenvalues, _ = np.linalg.eig(M)
    print(f"Eigenvalues: {eigenvalues}")

    if not np.isclose(det, 0):
        inv = np.linalg.inv(M)
        print(f"Inverse:\n{inv}")
    else:
        print("Inverse: Matrix is singular (determinant is 0).")
    print("\n")


analyze_matrix(A, "A")


B = A.copy()
B[0, 0] += 1
print("Element changed: Position (0, 0) was increased from 2 to 3.\n")

analyze_matrix(B, "B")

 Analysis for Matrix A
Matrix:
[[3. 8.]
 [2. 9.]]

Shape: (2, 2)
Determinant: 11.0000
Rank: 2
Eigenvalues: [ 1. 11.]
Inverse:
[[ 0.81818182 -0.72727273]
 [-0.18181818  0.27272727]]


Element changed: Position (0, 0) was increased from 2 to 3.

 Analysis for Matrix B
Matrix:
[[4. 8.]
 [2. 9.]]

Shape: (2, 2)
Determinant: 20.0000
Rank: 2
Eigenvalues: [ 1.78300943 11.21699057]
Inverse:
[[ 0.45 -0.4 ]
 [-0.1   0.2 ]]




### Comparison & Explanation

**a. Determinant Change:** The determinant increased from 14 to 21. Because the lower-left element is 0, the determinant is simply the product of the diagonal elements (A00 × A11). Increasing A00 from 2 to 3 directly scaled the determinant by 1 × 7 = +7.

**b. Rank Change:** The rank remained 2 for both matrices. Since both determinants are non-zero, the row and column vectors remain linearly independent, maintaining full rank.

**c. Eigenvalue Response:** The eigenvalues changed from [2,7] to [3,7]. Because both A and B are upper-triangular matrices, their eigenvalues directly equal their main diagonal entries. Altering A00 changed only the first eigenvalue.

**d. Invertibility Difficulty:** Both matrices have the exact same computational complexity to invert because both are non-singular 2x2 upper-triangular matrices with non-zero determinants.